apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gzac-frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/generiekzaakafhandelcomponent/helm-charts.git
    path: charts/gzac-frontend/gzac-frontend
    targetRevision: main
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts[0]:
            -host: gzac.example

  destination:    
    server: https://kubernetes.default.svc
    namespace: gzac-frontend

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
